# Generated by Django 4.1 on 2022-09-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_unified', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_unified', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('actors', models.ManyToManyField(to='database.actor')),
            ],
        ),
    ]
